<?php

/* page code for user role */
define('USER', '01');
define('USER_ROLE_PAGE', '09');
define('VENDOR_PAGE', '02');
define('RAW_CATEGORY_PAGE', '03');
define('RAW_PRODUCT_PAGE', '05');
define('RAW_STOCK_ENTRY_PAGE', '07');
define('FINISH_CATEGORY_PAGE', '04');
define('FINISH_PRODUCT_PAGE', '06');
define('PRODUCT_FURMULATION_PAGE', '08');
define('MIXING_RAW_MATERIAL_PAGE', '10');
define('EXTRA_RAW_LIFTING_PAGE', '11');
define('RAW_RETURN_PAGE', '12');
define('REPORT_RAW_STOCK', '13');
define('REPORT_RAW_STOCK_IN', '14');
define('REPORT_RAW_STOCK_OUT', '15');
define('REPORT_RAW_STOCK_IN_OUT', '16');

define('RAW_STOCK_CHECK_PAGE', '17');
define('RAW_STOCK_APPROVE_PAGE', '18');

define('RAW_STOCK_REPORT_PAGE', '19');

/* action code for user role */
define('RAW_STOCK_ADD', '01');  // RAW_STOCK_ENTRY_PAGE
define('RAW_STOCK_EDIT', '02');  // RAW_STOCK_ENTRY_PAGE
define('RAW_STOCK_CHECKED', '03');  // RAW_STOCK_ENTRY_PAGE
define('RAW_STOCK_APPRV', '04');  // RAW_STOCK_ENTRY_PAGE
define('RAW_STOCK_APPRV_UNLOCK', '05');  // RAW_STOCK_ENTRY_PAGE

define('FORMULA_ADD', '06');  // PRODUCT_FURMULATION_PAGE
define('FORMULA_EDIT', '07');  // PRODUCT_FURMULATION_PAGE
define('FORMULA_CHECKED', '08');  // PRODUCT_FURMULATION_PAGE
define('FORMULA_APPRV', '09');  // PRODUCT_FURMULATION_PAGE
define('FORMULA_APPRV_UNLOCK', '10');  // PRODUCT_FURMULATION_PAGE
define('FORMULA_RATE', '11');  // PRODUCT_FURMULATION_PAGE
define('FORMULA_ACTIVE_INACTIVE', '25');  // PRODUCT_FURMULATION_PAGE

define('MIXING_ADD', '12');  // MIXING_RAW_MATERIAL_PAGE
define('MIXING_EDIT', '13');  // MIXING_RAW_MATERIAL_PAGE
define('MIXING_CHECKED', '14');  // MIXING_RAW_MATERIAL_PAGE
define('MIXING_APPRV', '15');  // MIXING_RAW_MATERIAL_PAGE
define('MIXING_APPRV_UNLOCK', '16');  // MIXING_RAW_MATERIAL_PAGE

define('RAW_LIFTING_ADD', '17');  // EXTRA_RAW_LIFTING_PAGE
define('RAW_LIFTING_EDIT', '18');  // EXTRA_RAW_LIFTING_PAGE
define('RAW_LIFTING_CHECKED', '19');  // EXTRA_RAW_LIFTING_PAGE
define('RAW_LIFTING_APPRV', '20');  // EXTRA_RAW_LIFTING_PAGE
define('RAW_LIFTING_APPRV_UNLOCK', '21');  // EXTRA_RAW_LIFTING_PAGE

define('RAW_RETURN_ADD', '22');  // RAW_RETURN_PAGE
define('RAW_RETURN_CHECKED', '23');  // RAW_RETURN_PAGE
define('RAW_RETURN_APPRV', '24');  // RAW_RETURN_PAGE

define('REPORT_RAW_RATE', '26');  // REPORT_RAW_STOCK